/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.AI;
import Clases.Admin;
import Clases.Saga;
import Clases.Character;
import Clases.Global;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author alons
 */
public class Home extends javax.swing.JFrame {
    
    public static int id;
    public static Global g = new Global();
    private Saga starWars = new Saga(Global.starwarsName);
    private Saga starTrek = new Saga(Global.startrekName);
    AI ai = new AI(starWars, starTrek);
    Admin admin = new Admin(ai);
   
   
    
    

    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        starWars.setCharacter_list(g.star_wars_characters_names);
        starTrek.setCharacter_list(g.star_trek_characters_names);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        starWarsCard = new javax.swing.JLabel();
        starTrekCard = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jwinnersPane = new javax.swing.JScrollPane();
        winners = new javax.swing.JTextArea();
        ColaR_s22 = new javax.swing.JScrollPane();
        ColaR_s2 = new javax.swing.JTextArea();
        ColaR_s11 = new javax.swing.JScrollPane();
        ColaR_s1 = new javax.swing.JTextArea();
        ColaH_s22 = new javax.swing.JScrollPane();
        ColaH_s2 = new javax.swing.JTextArea();
        ColaM_s22 = new javax.swing.JScrollPane();
        ColaM_s2 = new javax.swing.JTextArea();
        ColaM_s11 = new javax.swing.JScrollPane();
        ColaM_s1 = new javax.swing.JTextArea();
        ColaL_s22 = new javax.swing.JScrollPane();
        ColaL_s2 = new javax.swing.JTextArea();
        ColaL_s11 = new javax.swing.JScrollPane();
        ColaL_s1 = new javax.swing.JTextArea();
        ColaH_s11 = new javax.swing.JScrollPane();
        ColaH_s1 = new javax.swing.JTextArea();
        stats1 = new javax.swing.JTextArea();
        stats2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        sliderTime = new javax.swing.JSlider();
        Fondo = new javax.swing.JLabel();
        character1 = new javax.swing.JLabel();
        character2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(147, 118, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 740, 180, 60));

        status.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("Status");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 590, -1));

        starWarsCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cards - Copy.png"))); // NOI18N
        starWarsCard.setText("jLabel3");
        jPanel1.add(starWarsCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 240, 340));

        starTrekCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cards.png"))); // NOI18N
        starTrekCard.setText("jLabel2");
        jPanel1.add(starTrekCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 250, 340));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(241, 193, 0));
        jLabel12.setText("Cola 1");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(241, 193, 0));
        jLabel13.setText("Cola 2");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(241, 193, 0));
        jLabel14.setText("Cola 3");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(241, 193, 0));
        jLabel15.setText("Cola de refuerzo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(241, 193, 0));
        jLabel11.setText("Cola de refuerzo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(241, 193, 0));
        jLabel10.setText("Cola 3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(241, 193, 0));
        jLabel9.setText("Cola 2");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(241, 193, 0));
        jLabel8.setText("Cola 1");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 193, 0));
        jLabel4.setText("VS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Velocidad de la IA (en segundos):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, -1, 30));

        jwinnersPane.setBackground(new java.awt.Color(0, 0, 0));
        jwinnersPane.setForeground(new java.awt.Color(0, 0, 0));

        winners.setEditable(false);
        winners.setBackground(new java.awt.Color(0, 0, 0));
        winners.setColumns(20);
        winners.setForeground(new java.awt.Color(255, 255, 255));
        winners.setRows(5);
        jwinnersPane.setViewportView(winners);

        jPanel1.add(jwinnersPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 420, 50));

        ColaR_s2.setEditable(false);
        ColaR_s2.setBackground(new java.awt.Color(0, 0, 0));
        ColaR_s2.setColumns(20);
        ColaR_s2.setForeground(new java.awt.Color(255, 255, 255));
        ColaR_s2.setRows(5);
        ColaR_s22.setViewportView(ColaR_s2);

        jPanel1.add(ColaR_s22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 190, 80));

        ColaR_s1.setEditable(false);
        ColaR_s1.setBackground(new java.awt.Color(0, 0, 0));
        ColaR_s1.setColumns(20);
        ColaR_s1.setForeground(new java.awt.Color(255, 255, 255));
        ColaR_s1.setRows(5);
        ColaR_s11.setViewportView(ColaR_s1);

        jPanel1.add(ColaR_s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, 80));

        ColaH_s2.setEditable(false);
        ColaH_s2.setBackground(new java.awt.Color(0, 0, 0));
        ColaH_s2.setColumns(20);
        ColaH_s2.setForeground(new java.awt.Color(255, 255, 255));
        ColaH_s2.setRows(5);
        ColaH_s22.setViewportView(ColaH_s2);

        jPanel1.add(ColaH_s22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 190, 80));

        ColaM_s2.setEditable(false);
        ColaM_s2.setBackground(new java.awt.Color(0, 0, 0));
        ColaM_s2.setColumns(20);
        ColaM_s2.setForeground(new java.awt.Color(255, 255, 255));
        ColaM_s2.setRows(5);
        ColaM_s22.setViewportView(ColaM_s2);

        jPanel1.add(ColaM_s22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 190, 80));

        ColaM_s1.setEditable(false);
        ColaM_s1.setBackground(new java.awt.Color(0, 0, 0));
        ColaM_s1.setColumns(20);
        ColaM_s1.setForeground(new java.awt.Color(255, 255, 255));
        ColaM_s1.setRows(5);
        ColaM_s11.setViewportView(ColaM_s1);

        jPanel1.add(ColaM_s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, 80));

        ColaL_s2.setEditable(false);
        ColaL_s2.setBackground(new java.awt.Color(0, 0, 0));
        ColaL_s2.setColumns(20);
        ColaL_s2.setForeground(new java.awt.Color(255, 255, 255));
        ColaL_s2.setRows(5);
        ColaL_s22.setViewportView(ColaL_s2);

        jPanel1.add(ColaL_s22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 190, 80));

        ColaL_s1.setEditable(false);
        ColaL_s1.setBackground(new java.awt.Color(0, 0, 0));
        ColaL_s1.setColumns(20);
        ColaL_s1.setForeground(new java.awt.Color(255, 255, 255));
        ColaL_s1.setRows(5);
        ColaL_s11.setViewportView(ColaL_s1);

        jPanel1.add(ColaL_s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, 80));

        ColaH_s1.setEditable(false);
        ColaH_s1.setBackground(new java.awt.Color(0, 0, 0));
        ColaH_s1.setColumns(20);
        ColaH_s1.setForeground(new java.awt.Color(255, 255, 255));
        ColaH_s1.setRows(5);
        ColaH_s11.setViewportView(ColaH_s1);

        jPanel1.add(ColaH_s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, 80));

        stats1.setBackground(new java.awt.Color(0, 0, 0));
        stats1.setColumns(20);
        stats1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        stats1.setForeground(new java.awt.Color(255, 255, 255));
        stats1.setRows(5);
        stats1.setText("skill:\nhealth:\nstrength:\nagility:");
        stats1.setBorder(null);
        stats1.setCaretColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(stats1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 230, 60));

        stats2.setBackground(new java.awt.Color(0, 0, 0));
        stats2.setColumns(20);
        stats2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        stats2.setForeground(new java.awt.Color(255, 255, 255));
        stats2.setRows(5);
        stats2.setText("skill:\nhealth:\nstrength:\nagility:");
        stats2.setBorder(null);
        jPanel1.add(stats2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 250, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lista de ganadores:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        sliderTime.setBackground(new java.awt.Color(255, 255, 255));
        sliderTime.setFont(new java.awt.Font("Phosphate", 1, 13)); // NOI18N
        sliderTime.setForeground(new java.awt.Color(255, 255, 255));
        sliderTime.setMajorTickSpacing(1);
        sliderTime.setMaximum(20);
        sliderTime.setMinimum(1);
        sliderTime.setPaintLabels(true);
        sliderTime.setPaintTicks(true);
        sliderTime.setSnapToTicks(true);
        sliderTime.setValue(10);
        sliderTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTimeStateChanged(evt);
            }
        });
        jPanel1.add(sliderTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, 770, 70));

        Fondo.setForeground(new java.awt.Color(60, 63, 65));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/background.png"))); // NOI18N
        Fondo.setText("jLabel1");
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 840));

        character1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        character1.setForeground(new java.awt.Color(255, 255, 255));
        character1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        character1.setText("Id: Nombre");
        jPanel1.add(character1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 720, 240, -1));

        character2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        character2.setForeground(new java.awt.Color(255, 255, 255));
        character2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        character2.setText("Id: Nombre");
        jPanel1.add(character2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JTextArea[] labels1 = new JTextArea[]{ColaH_s1, ColaM_s1, ColaL_s1, ColaR_s1};
        JTextArea[] labels2 = new JTextArea[]{ColaH_s2, ColaM_s2, ColaL_s2, ColaR_s2};
        JLabel[] cards = new JLabel[]{starWarsCard, starTrekCard};
        
        starWars.setTextAreas(labels1);
        starTrek.setTextAreas(labels2);
        
        starWars.setStats(stats1);
        starTrek.setStats(stats2);
        
        starWars.setTitle_lable(character1);
        starTrek.setTitle_lable(character2);
        
        admin.setCards(cards);
        
        for (int i = 0; i<20; i++){
            
            starWars.addCharacter(i);
            starTrek.addCharacter(i);
               
        }
        
        
        admin.start();
        ai.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sliderTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTimeStateChanged
        // TODO add your handling code here:
        ai.setWaitingTime(sliderTime.getValue() * 1000);
    }//GEN-LAST:event_sliderTimeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea ColaH_s1;
    private javax.swing.JScrollPane ColaH_s11;
    private javax.swing.JTextArea ColaH_s2;
    private javax.swing.JScrollPane ColaH_s22;
    private javax.swing.JTextArea ColaL_s1;
    private javax.swing.JScrollPane ColaL_s11;
    private javax.swing.JTextArea ColaL_s2;
    private javax.swing.JScrollPane ColaL_s22;
    private javax.swing.JTextArea ColaM_s1;
    private javax.swing.JScrollPane ColaM_s11;
    private javax.swing.JTextArea ColaM_s2;
    private javax.swing.JScrollPane ColaM_s22;
    private javax.swing.JTextArea ColaR_s1;
    private javax.swing.JScrollPane ColaR_s11;
    private javax.swing.JTextArea ColaR_s2;
    private javax.swing.JScrollPane ColaR_s22;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel character1;
    private javax.swing.JLabel character2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jwinnersPane;
    private javax.swing.JSlider sliderTime;
    private javax.swing.JLabel starTrekCard;
    private javax.swing.JLabel starWarsCard;
    private javax.swing.JTextArea stats1;
    private javax.swing.JTextArea stats2;
    public static javax.swing.JLabel status;
    public static javax.swing.JTextArea winners;
    // End of variables declaration//GEN-END:variables
}
